---
title: "DataVis_Group_Final"
output: html_document
date: "2023-11-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggtext)
library(showtext)

```


```{r, warning=FALSE}

# Win percentage of the English national team over the years

int_games <- read_csv('C:/Users/thoma/Documents/AAA Thomas/School/LBS/Term1/Data Visualisation and Story Telling/am10.mam2023-main/Group Project/int_games.csv')

winning_teams <- int_games %>% 
  distinct(date, home_team, away_team, .keep_all = TRUE) %>%
  group_by(date, home_team, away_team) %>% 
  summarise(home_score, away_score) %>% 
  mutate(winning_team = if_else(home_score > away_score, home_team, if_else(home_score < away_score, away_team, "Draw")))

win_percentage <- winning_teams %>% 
  group_by(year = year(date)) %>% 
  filter(year > 2000) %>% 
  summarise(total_games = n(), 
            total_wins = sum(winning_team == "England"), 
            win_percentage = (total_wins/total_games)*100) %>% 
  mutate(average = mean(win_percentage))

win_perc_plot <- win_percentage %>% 
  ggplot() +
  geom_line(aes(x = year, y = win_percentage), colour = "darkblue", size = 1) +
  theme_minimal() +
  labs(title = 
      "<b>The Three Lions have <span style='color:tomato'>won over 60% of their games</span> since 2001</b><br>
      <span style='font-size:12pt;color:darkblue'>Yearly win percentage of the English national team between 2001 and 2023</span>",
      x = NULL,
      y = NULL) +
  theme(plot.title = element_textbox_simple(size = 16, colour = "grey15", margin = margin(t = 10, b = 10)),
        axis.text.x = element_text(hjust = 0.5),
        axis.ticks.x = element_line(color = "grey15"),
        text = element_text(size = 12, family = "Montserrat")) +
  geom_hline(aes(yintercept = average), linetype = "dotted", color = "tomato", size = 1) +
  geom_text(data = data.frame(x = 2023, y = 63.5, label = "61.27%"),
            aes(x = x, y = y, label = label),
            family="Montserrat",
            colour = "tomato",
            size = 4,
            hjust = 0,
            lineheight = .8,
            inherit.aes = FALSE,
            fontface = "bold") +
  lims(x = c(2001, 2024)) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  theme(plot.margin = margin(r = 10, l = 10))

win_perc_plot

```


```{r}

# Correlation with stock prices?

FTSE_100 <- read_csv('C:/Users/thoma/Documents/AAA Thomas/School/LBS/Term1/Data Visualisation and Story Telling/am10.mam2023-main/Group Project/FTSE 100 Historical Data.csv')

yearly_stockprice_change <- FTSE_100 %>% 
  mutate(Date = as.Date(Date, format = "%d/%m/%Y")) %>% 
  group_by(year = year(Date)) %>% 
  summarise(price = Price[which.max(Date)])
  
  
#  summarise(Earliest_price = Open[which.min(Date)],
#            Latest_price = Price[which.max(Date)]) %>% 
#  mutate(change = (Latest_price/Earliest_price - 1)*100)

win_perc_stock_change <- yearly_stockprice_change %>% 
  left_join(win_percentage, by='year') %>% 
  select(year, price, win_percentage)

correlation_matrix <- cor(win_perc_stock_change$price, win_perc_stock_change$win_percentage)
print(correlation_matrix)



plot_win_stock <- win_perc_stock_change %>% 
  ggplot() +
  geom_point(aes(x = win_percentage, y = price)) +
  geom_smooth(aes(x = win_percentage, y = price))

plot_win_stock

```

